#ifndef COMMON_WIRING_CONFIG_HPP
#define COMMON_WIRING_CONFIG_HPP

#define UNCONNECTED = -1;
#define GROUNDED = 0
#define CONNECTED = 1;
#define PULLED_HIGH = 2;

#define HYPER_PIN_D0 = UNCONNECTED
#define HYPER_PIN_D1 = UNCONNECTED
#define HYPER_PIN_D2 = UNCONNECTED
#define HYPER_PIN_D3 = UNCONNECTED
#define HYPER_PIN_D4 = UNCONNECTED
#define HYPER_PIN_D5 = UNCONNECTED
#define HYPER_PIN_D6 = UNCONNECTED
#define HYPER_PIN_D7 = UNCONNECTED
#define HYPER_PIN_D8 = UNCONNECTED
#define HYPER_PIN_D9 = UNCONNECTED
#define HYPER_PIN_D10 = UNCONNECTED
#define HYPER_PIN_D11 = UNCONNECTED
#define HYPER_PIN_D12 = UNCONNECTED
#define HYPER_PIN_D13 = UNCONNECTED

#define HYPER_PIN_A0 = UNCONNECTED
#define HYPER_PIN_A1 = UNCONNECTED
#define HYPER_PIN_A2 = UNCONNECTED
#define HYPER_PIN_A3 = UNCONNECTED
#define HYPER_PIN_A4 = UNCONNECTED
#define HYPER_PIN_A5 = UNCONNECTED

#endif /* COMMON_WIRING_CONFIG_HPP */